version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=superSecretDBPassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=posts_db
    ports:
      - 5432:5432
    networks:
      - myshared-network
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data

  server:
    container_name: posts_manager
    restart: unless-stopped
    image: posts_manager:1.0.0
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - myshared-network
    depends_on:
      - db

  client:
    container_name: posts-manager-client
    restart: unless-stopped
    image: posts-manager-client:1.0.0
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - myshared-network
    depends_on:
      - server

  # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=placeholder@example.com
      - PGADMIN_DEFAULT_PASSWORD=fakepassword123!
    ports:
      - 16543:80
    depends_on:
      - db
    links:
      - db
    networks:
      - myshared-network

networks:
  myshared-network:

# volumes:
#   pgdata: {}
